# Generated by Django 3.2.7 on 2021-12-13 21:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'sony'), ('canon', 'canon'), ('nikon', 'nikon'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('others', 'others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('Programing', 'Programing'), ('Teaching', 'Teaching'), ('Vlogs', 'Vlogs'), ('Music', 'Music'), ('Reviews', 'Reviews')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='subs_count',
            field=models.IntegerField(),
        ),
    ]
