# Generated by Django 3.1.7 on 2021-03-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
