# Generated by Django 3.1.7 on 2021-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'sony'), ('canon', 'canon'), ('nikon', 'nikon'), ('panasonic', 'panasonic'), ('red', 'red'), ('fuji', 'fuji'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Vloggers', 'Vloggers'), ('Music', 'Music'), ('Mobile_Unboxing', 'Mobile_Unboxing'), ('Comedy', 'Comedy'), ('Gaming', 'Gaming'), ('Cooking', 'Cooking'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('solo', 'solo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='height',
            field=models.IntegerField(),
        ),
    ]
