# Generated by Django 3.1.7 on 2021-03-16 15:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210316_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
